install.packages(shiny)
install.packages(bslib)
install.packages(DT)
install.packages(httr)
install.packages(jsonlite)
install.packages(data.table)
install.packages(mongolite)
# install.packages(shinycssloaders)
# install.packages(quarto)
install.packages(RMySQL)
install.packages(stringr)
